// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliclinicaHope.Data;

#nullable disable

namespace PoliclinicaHope.Migrations
{
    [DbContext(typeof(PoliclinicaHopeContext))]
    [Migration("20250112214253_PROGRAMARI")]
    partial class PROGRAMARI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoliclinicaHope.Models.Departament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DepartamentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.DepartamentProcedura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<int>("ProceduraId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("ProceduraId");

                    b.ToTable("DepartamentProcedura");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Medic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MedicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medic");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Pacient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pacient");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Procedura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicId")
                        .HasColumnType("int");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MedicId");

                    b.ToTable("Procedura");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Programare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PacientId")
                        .HasColumnType("int");

                    b.Property<int?>("ProceduraID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PacientId");

                    b.HasIndex("ProceduraID");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.DepartamentProcedura", b =>
                {
                    b.HasOne("PoliclinicaHope.Models.Departament", "Departament")
                        .WithMany("DepartamenteProceduri")
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliclinicaHope.Models.Procedura", "Procedura")
                        .WithMany("DepartamenteProceduri")
                        .HasForeignKey("ProceduraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");

                    b.Navigation("Procedura");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Procedura", b =>
                {
                    b.HasOne("PoliclinicaHope.Models.Medic", "Medic")
                        .WithMany("Proceduri")
                        .HasForeignKey("MedicId");

                    b.Navigation("Medic");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Programare", b =>
                {
                    b.HasOne("PoliclinicaHope.Models.Pacient", "Pacient")
                        .WithMany("Programari")
                        .HasForeignKey("PacientId");

                    b.HasOne("PoliclinicaHope.Models.Procedura", "Procedura")
                        .WithMany("Programari")
                        .HasForeignKey("ProceduraID");

                    b.Navigation("Pacient");

                    b.Navigation("Procedura");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Departament", b =>
                {
                    b.Navigation("DepartamenteProceduri");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Medic", b =>
                {
                    b.Navigation("Proceduri");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Pacient", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Procedura", b =>
                {
                    b.Navigation("DepartamenteProceduri");

                    b.Navigation("Programari");
                });
#pragma warning restore 612, 618
        }
    }
}
