// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliclinicaHope.Data;

#nullable disable

namespace PoliclinicaHope.Migrations
{
    [DbContext(typeof(PoliclinicaHopeContext))]
    partial class PoliclinicaHopeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoliclinicaHope.Models.Medic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MedicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medic");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Procedura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicId")
                        .HasColumnType("int");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MedicId");

                    b.ToTable("Procedura");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Procedura", b =>
                {
                    b.HasOne("PoliclinicaHope.Models.Medic", "Medic")
                        .WithMany("Proceduri")
                        .HasForeignKey("MedicId");

                    b.Navigation("Medic");
                });

            modelBuilder.Entity("PoliclinicaHope.Models.Medic", b =>
                {
                    b.Navigation("Proceduri");
                });
#pragma warning restore 612, 618
        }
    }
}
